spring:
  profiles:
    active: local #local,dev,real
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@211.63.89.70:1521:xe
    username: fuser04
    password: f1234
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      
  messages:
    basename: hjw.properties,ksh.properties,kts.properties,ljy.properties,psk.properties,ysb.properties,ysw.properties
    encoding: UTF-8
    
  devtools:
    livereload:
      enabled: true
      
    restart:
      enabled: true
      
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

  oauth2:
    client:
      registration:
        naver:
          client-id: bIwCvJnI1r_XLOaITYqT
          client-secret: zx5A_1_BQ9
          redirect-uri: http://localhost:8000/login/oauth2/code/naver
          authorization-grant-type: authorization_code
          scope: name, email
          client-name: naver
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response.id
mybatis:
  type-aliases-package: kr.spring.**.vo
  mapper-locations: kr/spring/**/dao/*.xml
    
logging:
  level:
    '[kr.spring]': debug
    
server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true    
  tomcat:
    max-http-form-post-size: 200MB
    
    
